WITH RECURSIVE PARENT AS
(
    SELECT ID, PARENT_ID, 1 AS DEPTH
      FROM ECOLI_DATA
     WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT ED.ID, ED.PARENT_ID, P.DEPTH + 1
      FROM PARENT P
      JOIN ECOLI_DATA ED ON P.ID = ED.PARENT_ID
)

SELECT ID
  FROM PARENT
 WHERE DEPTH = 3