SELECT B.ITEM_ID, A.ITEM_NAME, A.RARITY
  FROM ITEM_INFO AS A
  JOIN ITEM_TREE AS B ON A.ITEM_ID = B.ITEM_ID
 WHERE NOT EXISTS
       (
           SELECT 1
             FROM ITEM_TREE T
            WHERE T.PARENT_ITEM_ID = B.ITEM_ID
       )
 ORDER BY B.ITEM_ID DESC;
