SELECT A.CAR_ID, A.CAR_TYPE, CAST(A.DAILY_FEE * (100 - C.DISCOUNT_RATE) / 100 * 30 AS UNSIGNED) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR A
  JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
    ON A.CAR_TYPE = C.CAR_TYPE
   AND C.DURATION_TYPE = '30일 이상'
 WHERE A.CAR_TYPE IN ('세단', 'SUV')
   AND NOT EXISTS
       (
         SELECT 1
           FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
          WHERE H.CAR_ID = A.CAR_ID
            AND H.START_DATE <= '2022-11-30'
            AND H.END_DATE   >= '2022-11-01'
       )
   AND A.DAILY_FEE * (100 - C.DISCOUNT_RATE) / 100 * 30 BETWEEN 500000 AND 1999999
 ORDER BY FEE DESC, A.CAR_TYPE ASC, A.CAR_ID DESC;
