-- 코드를 작성해주세요
SELECT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
  FROM DEVELOPER_INFOS AS A
 WHERE 'Python' IN (SELECT A.SKILL_1)
    OR 'Python' IN (SELECT A.SKILL_2)
    OR 'Python' IN (SELECT A.SKILL_3)
 ORDER BY A.ID