WITH RECURSIVE PARENT AS
(
    SELECT ID, PARENT_ID, 1 AS DEPTH
      FROM ECOLI_DATA
     WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT ED.ID, ED.PARENT_ID, P.DEPTH + 1
      FROM PARENT P
      JOIN ECOLI_DATA ED ON P.ID = ED.PARENT_ID
)

SELECT COUNT(*) AS COUNT, DEPTH AS GENERATION
  FROM PARENT
 WHERE ID NOT IN (SELECT PARENT_ID FROM ECOLI_DATA WHERE PARENT_ID IS NOT NULL)
 GROUP BY DEPTH
 ORDER BY DEPTH;