WITH RECURSIVE PARENT AS
(
    SELECT ID, PARENT_ID, 0 AS DEPTH
      FROM ECOLI_DATA
     WHERE PARENT_ID IS NULL

    UNION ALL

    SELECT ED.ID, ED.PARENT_ID, P.DEPTH + 1 AS DEPTH
      FROM PARENT P
      LEFT OUTER JOIN ECOLI_DATA ED ON P.ID = ED.PARENT_ID
     WHERE P.ID IS NOT NULL
)


SELECT COUNT(1) AS COUNT, DEPTH GENERATION
  FROM PARENT
 WHERE ID IS NULL
 GROUP BY ID, DEPTH
 ORDER BY DEPTH
