SELECT DISTINCT A.ID, A.EMAIL, A.FIRST_NAME, A.LAST_NAME
FROM
(
    SELECT B.*, C.CODE
      FROM DEVELOPERS B
      JOIN SKILLCODES C ON C.NAME = 'Python'
                        OR C.NAME = 'C#'
) A
WHERE A.SKILL_CODE & A.CODE != 0
ORDER BY A.ID ASC