SELECT A.ID, B.FISH_NAME, A.LENGTH
  FROM FISH_INFO AS A
  JOIN FISH_NAME_INFO AS B  ON A.FISH_TYPE = B.FISH_TYPE
 WHERE A.LENGTH IN
       (
           SELECT MAX(A2.LENGTH)
             FROM FISH_INFO AS A2
             JOIN FISH_NAME_INFO AS B2 ON A2.FISH_TYPE = B2.FISH_TYPE
            WHERE B2.FISH_NAME = B.FISH_NAME
       );
