SELECT G.SCORE,
       E.EMP_NO,
       E.EMP_NAME,
       E.POSITION,
       E.EMAIL
  FROM HR_EMPLOYEES E
  JOIN
  (
      SELECT EMP_NO, SUM(SCORE) AS SCORE
      FROM HR_GRADE
      WHERE YEAR = 2022
      GROUP BY EMP_NO
  ) AS G ON E.EMP_NO = G.EMP_NO
 WHERE G.SCORE =
 (
    SELECT MAX(SUM_SCORE)
    FROM
    (
        SELECT EMP_NO, SUM(SCORE) AS SUM_SCORE
        FROM HR_GRADE
        WHERE YEAR = 2022
        GROUP BY EMP_NO
    ) AS X
 )
 ORDER BY E.EMP_NO;
