SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD') AS CREATED_DATE
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_REPLY B ON A.BOARD_ID = B.BOARD_ID
WHERE TO_CHAR(A.CREATED_DATE, 'YYYY-MM-DD') BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY TO_CHAR(B.CREATED_DATE, 'YYYY-MM-DD'), TITLE;