SELECT CATEGORY, PRICE AS MAX_PRICE, PRODUCT_NAME
  FROM FOOD_PRODUCT F1
 WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
  AND PRICE =
  (
      SELECT MAX(PRICE)
      FROM FOOD_PRODUCT F2
      WHERE F2.CATEGORY = F1.CATEGORY
  )
 ORDER BY PRICE DESC;
